### ISSUE TITLE
downloaded file damaged

### ISSUE THREAD

**Issue by blossomzx** [wri/restoration-mapper#1]
Hello, why is the downloaded zip file damaged?I can't get the files in src.Could you help me? Thank you very much!

**Comment by JohnMBrandt** [comment]
Hi this repository is still an unpublished research project and the data is not publicly released. The src/download_data.py file is outdated and the code has not been released as src files yet.

**Comment by JohnMBrandt** [comment]
Hi - the preprint of the pub is available now:

https://arxiv.org/pdf/2005.08702.pdf

The readme has been updated with a docker container if you wish to adapt the code.
